version: '3.8'

services:
  backend:
    build: .
    container_name: quiz_backend
    restart: always
    # depends_on:
    #   database:
    #     condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql://quizuser:quizpassword@database:5433/quizdb'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
